### ISSUE TITLE
Unable to deserialize config file: /config.json

### ISSUE THREAD

**Issue by DavidePastore** [triaxtec/openapitools-generator-action#18]
I'm trying to generate a PHP client using a specific configuration file that is part of my repository.

The following [is working](https://github.com/DavidePastore/channelengine-merchant-api-client-php-openapi-generator/actions/runs/5113950693/jobs/9193710384) (explicit version declaration for the **openapitools-generator-action** action):

```
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  generate-php-client:
    runs-on: ubuntu-latest
    name: Generate PHP Client
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the version
        id: set-version
        run: |
          wget -O swagger.json "https://demo.channelengine.net/api/swagger/merchant/swagger.json"
          version=$(cat swagger.json | jq '.info.version')
          echo "The version is ${version}"
          echo "packageVersion=${version}" >> $GITHUB_OUTPUT


      # Generate your OpenAPI document (if you don't write it manually)

      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate PHP Client
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: php
          openapi-url: "https://demo.channelengine.net/api/swagger/merchant/swagger.json"
          config-file: /config.json
          command-args: --artifact-version=${{ steps.set-version.outputs.packageVersion }}
```

If I try to use v1 instead of v1.3.0 (so, using the latest available version), I get [the following error](https://github.com/DavidePastore/channelengine-merchant-api-client-php-openapi-generator/actions/runs/5113900112/jobs/9193609716):

> Digest: sha256:45515b497db7b78[54](https://github.com/DavidePastore/channelengine-merchant-api-client-php-openapi-generator/actions/runs/5113900112/jobs/9193609716#step:4:56)16f23b24309aea282[58](https://github.com/DavidePastore/channelengine-merchant-api-client-php-openapi-generator/actions/runs/5113900112/jobs/9193609716#step:4:60)edbd8029dde183b92fb2f6884f68
> Status: Downloaded newer image for openapitools/openapi-generator-cli:latest
> [main] ERROR o.o.c.config.CodegenConfigurator - /config.json (No such file or directory)
> [main] ERROR o.o.c.config.CodegenConfigurator - /config.json (No such file or directory)
> Exception in thread "main" java.lang.RuntimeException: Unable to deserialize config file: /config.json
> 	at org.openapitools.codegen.config.CodegenConfigurator.readDynamicSettings(CodegenConfigurator.java:171)
> 	at org.openapitools.codegen.config.CodegenConfigurator.fromFile(CodegenConfigurator.java:90)
> 	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:314)
> 	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
> 	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
> Error: Process completed with exit code 1.

Could you please fix this behavior? Thanks in advance!
