### ISSUE TITLE
Remote openapi specs not supported

### ISSUE THREAD

**Issue by carschno** [triaxtec/openapitools-generator-action#2]
I can generate an Openapi client from a remote location like this:

    java -jar openapi-generator-cli-5.2.0.jar generate -i http://some.url.com/openapi.json

However, when I specify a remote URL into the `openapi-file` setting in the Github action, I get this error:

    Error:  The spec file is not found: /github/workspace/http://some.url.com/openapi.json

This is my workflow:
```
generate_client:
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate Java client
        uses: triaxtec/openapitools-generator-action@v1.0.0
        with:
          generator: java
          config-file: openapi-generator-java.yml
          openapi-file: http://some.url.com/openapi.json
```

This looks like the OpenAPI file location should not be prefixed with `/github/workspace/` if it is a remote location.
